apiVersion: v1
kind: Secret
metadata:
  name: sec-app
  namespace: {{ .Release.Namespace | default "app" }}
type: Opaque
stringData:
  PG_HOST: {{ .Values.secret.PG_HOST | quote }}
  PG_PORT: {{ .Values.secret.PG_PORT | quote }}
  PG_NAME: {{ .Values.secret.PG_NAME | quote }}
  PG_USER: {{ .Values.secret.PG_USER | quote }}
  PG_PASSWORD: {{ .Values.secret.PG_PASSWORD | quote }}
