- name: postgres-master playbook
  hosts: master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  roles:
    - postgres-master

# - name: postgres-slave playbook
#   hosts: data_base
#   become: yes
#   become_user: root
#   become_method: sudo
#   gather_facts: false
#   roles:
#     - postgres-slave


