version: "3"

dotenv:
  - ".env"

tasks:
  up:
    cmds:
      - docker compose up --build -d
  
  down:
    cmds:
      - docker compose down

  # restart:
  #   cmds:
  #     - task: down
  #     - task: up
