version: "3"

dotenv:
  - ".env"

tasks:
  up:
    cmds:
      - docker compose up --build -d
  
  down:
    cmds:
      - docker compose down

  restart:
    cmds:
      - task: down
      - task: up


  push:
    cmds:
      - docker tag laba3-flask:latest lendy1/laba3-flask:latest
      - docker push lendy1/laba3-flask:latest
